#pragma once
#include <_isim_cdefs.h>
__BEGIN_DECLS
extern int *__error(void);
__END_DECLS
#define errno (*__error())
#define EPERM 1
#define ENOENT 2
#define EINTR 4
#define EIO 5
#define ENOMEM 12
#define EACCES 13
#define EBUSY 16
#define EEXIST 17
#define EINVAL 22
#define EAGAIN 35
#define ETIMEDOUT 60
#define ESRCH 3
#define E2BIG 7
#define EBADF 9
#define ECHILD 10
#define EDEADLK 11
#define EFAULT 14
#define ENOTDIR 20
#define EISDIR 21
#define ENFILE 23
#define EMFILE 24
#define ENOSPC 28
#define ERANGE 34
#define EDOM 33
#define EWOULDBLOCK EAGAIN
#define EINPROGRESS 36
#define ENOTSUP 45
#define ENOSYS 78
#define EOVERFLOW 84
#define ECANCELED 89
#define EILSEQ 92
#define EPIPE 32
#define EALREADY 37
#define ENOTSOCK 38
#define EDESTADDRREQ 39
#define EMSGSIZE 40
#define EPROTOTYPE 41
#define ENOPROTOOPT 42
#define EPROTONOSUPPORT 43
#define ESOCKTNOSUPPORT 44
#define EPFNOSUPPORT 46
#define EAFNOSUPPORT 47
#define EADDRINUSE 48
#define EADDRNOTAVAIL 49
#define ENETDOWN 50
#define ENETUNREACH 51
#define ENETRESET 52
#define ECONNABORTED 53
#define ECONNRESET 54
#define ENOBUFS 55
#define EISCONN 56
#define ENOTCONN 57
#define ESHUTDOWN 58
#define ECONNREFUSED 61
#define EHOSTDOWN 64
#define EHOSTUNREACH 65
#define EOPNOTSUPP 102
