#pragma once
/* isim SDK math.h (C11 subset, Darwin constant values). Generated by gen in this dir. */
#include <_isim_cdefs.h>
__BEGIN_DECLS
typedef float float_t;
typedef double double_t;
#define HUGE_VAL __builtin_huge_val()
#define HUGE_VALF __builtin_huge_valf()
#define HUGE_VALL __builtin_huge_vall()
#define INFINITY __builtin_inff()
#define NAN __builtin_nanf("")
#define FP_NAN 1
#define FP_INFINITE 2
#define FP_ZERO 3
#define FP_NORMAL 4
#define FP_SUBNORMAL 5
#define FP_SUPERNORMAL 6
#define FP_ILOGB0 (-2147483647 - 1)
#define FP_ILOGBNAN (-2147483647 - 1)
#define MATH_ERRNO 1
#define MATH_ERREXCEPT 2
#define math_errhandling MATH_ERREXCEPT
#define fpclassify(x) __builtin_fpclassify(FP_NAN, FP_INFINITE, FP_NORMAL, FP_SUBNORMAL, FP_ZERO, x)
#define isnan(x) __builtin_isnan(x)
#define isinf(x) __builtin_isinf(x)
#define isfinite(x) __builtin_isfinite(x)
#define isnormal(x) __builtin_isnormal(x)
#define signbit(x) __builtin_signbit(x)
#define isgreater(x, y) __builtin_isgreater(x, y)
#define isgreaterequal(x, y) __builtin_isgreaterequal(x, y)
#define isless(x, y) __builtin_isless(x, y)
#define islessequal(x, y) __builtin_islessequal(x, y)
#define islessgreater(x, y) __builtin_islessgreater(x, y)
#define isunordered(x, y) __builtin_isunordered(x, y)
#define M_E 2.71828182845904523536028747135266250
#define M_LOG2E 1.44269504088896340735992468100189214
#define M_LOG10E 0.434294481903251827651128918916605082
#define M_LN2 0.693147180559945309417232121458176568
#define M_LN10 2.30258509299404568401799145468436421
#define M_PI 3.14159265358979323846264338327950288
#define M_PI_2 1.57079632679489661923132169163975144
#define M_PI_4 0.785398163397448309615660845819875721
#define M_1_PI 0.318309886183790671537767526745028724
#define M_2_PI 0.636619772367581343075535053490057448
#define M_2_SQRTPI 1.12837916709551257389615890312154517
#define M_SQRT2 1.41421356237309504880168872420969808
#define M_SQRT1_2 0.707106781186547524400844362104849039
double acos(double); float acosf(float); long double acosl(long double);
double asin(double); float asinf(float); long double asinl(long double);
double atan(double); float atanf(float); long double atanl(long double);
double cos(double); float cosf(float); long double cosl(long double);
double sin(double); float sinf(float); long double sinl(long double);
double tan(double); float tanf(float); long double tanl(long double);
double acosh(double); float acoshf(float); long double acoshl(long double);
double asinh(double); float asinhf(float); long double asinhl(long double);
double atanh(double); float atanhf(float); long double atanhl(long double);
double cosh(double); float coshf(float); long double coshl(long double);
double sinh(double); float sinhf(float); long double sinhl(long double);
double tanh(double); float tanhf(float); long double tanhl(long double);
double exp(double); float expf(float); long double expl(long double);
double exp2(double); float exp2f(float); long double exp2l(long double);
double expm1(double); float expm1f(float); long double expm1l(long double);
double log(double); float logf(float); long double logl(long double);
double log10(double); float log10f(float); long double log10l(long double);
double log1p(double); float log1pf(float); long double log1pl(long double);
double log2(double); float log2f(float); long double log2l(long double);
double logb(double); float logbf(float); long double logbl(long double);
double cbrt(double); float cbrtf(float); long double cbrtl(long double);
double fabs(double); float fabsf(float); long double fabsl(long double);
double sqrt(double); float sqrtf(float); long double sqrtl(long double);
double erf(double); float erff(float); long double erfl(long double);
double erfc(double); float erfcf(float); long double erfcl(long double);
double lgamma(double); float lgammaf(float); long double lgammal(long double);
double tgamma(double); float tgammaf(float); long double tgammal(long double);
double ceil(double); float ceilf(float); long double ceill(long double);
double floor(double); float floorf(float); long double floorl(long double);
double nearbyint(double); float nearbyintf(float); long double nearbyintl(long double);
double rint(double); float rintf(float); long double rintl(long double);
double round(double); float roundf(float); long double roundl(long double);
double trunc(double); float truncf(float); long double truncl(long double);
double atan2(double, double); float atan2f(float, float); long double atan2l(long double, long double);
double hypot(double, double); float hypotf(float, float); long double hypotl(long double, long double);
double pow(double, double); float powf(float, float); long double powl(long double, long double);
double fmod(double, double); float fmodf(float, float); long double fmodl(long double, long double);
double remainder(double, double); float remainderf(float, float); long double remainderl(long double, long double);
double copysign(double, double); float copysignf(float, float); long double copysignl(long double, long double);
double nextafter(double, double); float nextafterf(float, float); long double nextafterl(long double, long double);
double fdim(double, double); float fdimf(float, float); long double fdiml(long double, long double);
double fmax(double, double); float fmaxf(float, float); long double fmaxl(long double, long double);
double fmin(double, double); float fminf(float, float); long double fminl(long double, long double);
double frexp(double, int *); float frexpf(float, int *); long double frexpl(long double, int *);
double ldexp(double, int); float ldexpf(float, int); long double ldexpl(long double, int);
double modf(double, double *); float modff(float, float *); long double modfl(long double, long double *);
double scalbn(double, int); float scalbnf(float, int); long double scalbnl(long double, int);
double scalbln(double, long); float scalblnf(float, long); long double scalblnl(long double, long);
int ilogb(double); int ilogbf(float); int ilogbl(long double);
long lrint(double); long lrintf(float); long lrintl(long double);
long long llrint(double); long long llrintf(float); long long llrintl(long double);
long lround(double); long lroundf(float); long lroundl(long double);
long long llround(double); long long llroundf(float); long long llroundl(long double);
double remquo(double, double, int *); float remquof(float, float, int *); long double remquol(long double, long double, int *);
double nan(const char *); float nanf(const char *); long double nanl(const char *);
double nexttoward(double, long double); float nexttowardf(float, long double); long double nexttowardl(long double, long double);
double fma(double, double, double); float fmaf(float, float, float); long double fmal(long double, long double, long double);
__END_DECLS
