// isim CryptoKit: private-key DER/PEM (PKCS#8, also reads SEC1 "EC PRIVATE KEY") and compact representations
// (draft-jivsov-ecc-compact: the x coordinate alone, for keys whose y is the smaller square root) for the NIST curves.
// Generated by hand from one template per curve; see _ECKeyCoding below for the encoders.
import Foundation

enum _ECKeyCoding {
    static func oid(_ curve: Int32) -> [UInt8] {
        switch curve {
        case 256: return [0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07]
        case 384: return [0x06, 0x05, 0x2b, 0x81, 0x04, 0x00, 0x22]
        default: return [0x06, 0x05, 0x2b, 0x81, 0x04, 0x00, 0x23]
        }
    }
    static let ecPublicKeyOID: [UInt8] = [0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01]
    static func len(_ n: Int) -> [UInt8] {
        if n < 0x80 { return [UInt8(n)] }
        if n < 0x100 { return [0x81, UInt8(n)] }
        return [0x82, UInt8(n >> 8), UInt8(n & 0xff)]
    }
    static func tlv(_ tag: UInt8, _ body: [UInt8]) -> [UInt8] { [tag] + len(body.count) + body }
    /// PKCS#8 PrivateKeyInfo wrapping a SEC1 ECPrivateKey (with the public key), like CryptoKit's derRepresentation
    static func pkcs8(_ curve: Int32, d: [UInt8], q: [UInt8]) -> [UInt8] {
        let sec1 = tlv(0x30, [0x02, 0x01, 0x01] + tlv(0x04, d) + tlv(0xa1, tlv(0x03, [0x00] + q)))
        let alg = tlv(0x30, ecPublicKeyOID + oid(curve))
        return tlv(0x30, [0x02, 0x01, 0x00] + alg + tlv(0x04, sec1))
    }
    /// reads one TLV at i; returns (tag, body range)
    static func read(_ b: [UInt8], _ i: inout Int) throws -> (UInt8, Range<Int>) {
        guard i + 2 <= b.count else { throw CryptoKitError.invalidParameter }
        let tag = b[i]; var n = Int(b[i + 1]); i += 2
        if n & 0x80 != 0 {
            let k = n & 0x7f; guard k >= 1, k <= 3, i + k <= b.count else { throw CryptoKitError.invalidParameter }
            n = 0; for _ in 0..<k { n = n << 8 | Int(b[i]); i += 1 }
        }
        guard i + n <= b.count else { throw CryptoKitError.invalidParameter }
        defer { i += n }
        return (tag, i..<(i + n))
    }
    /// the private scalar from PKCS#8 or SEC1 DER
    static func privateScalar(_ curve: Int32, _ der: [UInt8]) throws -> [UInt8] {
        var i = 0
        let (t, outer) = try read(der, &i)
        guard t == 0x30 else { throw CryptoKitError.invalidParameter }
        var j = outer.lowerBound
        let (vt, vr) = try read(der, &j)
        guard vt == 0x02 else { throw CryptoKitError.invalidParameter }
        let version = der[vr].last ?? 0
        var sec1: [UInt8]
        if version == 0 {     // PKCS#8: AlgorithmIdentifier then OCTET STRING { ECPrivateKey }
            let (at, ar) = try read(der, &j)
            guard at == 0x30, Array(der[ar]).starts(with: ecPublicKeyOID) else { throw CryptoKitError.invalidParameter }
            let curveOID = Array(der[ar].dropFirst(ecPublicKeyOID.count))
            guard curveOID.isEmpty || curveOID == oid(curve) else { throw CryptoKitError.incorrectKeySize }
            let (ot, or) = try read(der, &j)
            guard ot == 0x04 else { throw CryptoKitError.invalidParameter }
            sec1 = Array(der[or])
        } else { sec1 = der }
        var k = 0
        let (st, sr) = try read(sec1, &k)
        guard st == 0x30 else { throw CryptoKitError.invalidParameter }
        var m = sr.lowerBound
        _ = try read(sec1, &m)                        // version 1
        let (dt, dr) = try read(sec1, &m)
        guard dt == 0x04 else { throw CryptoKitError.invalidParameter }
        let d = Array(sec1[dr]), n = _EC.size(curve)
        guard d.count <= n else { throw CryptoKitError.incorrectKeySize }
        return [UInt8](repeating: 0, count: n - d.count) + d
    }
    static func pemBody(_ pem: String) throws -> [UInt8] {
        if let d = try? _fromPEM(pem, "PRIVATE KEY") { return d }
        return try _fromPEM(pem, "EC PRIVATE KEY")
    }

    // compact representation
    static func prime(_ curve: Int32) -> [UInt8] {
        switch curve {
        case 256: return _hex("ffffffff00000001000000000000000000000000ffffffffffffffffffffffff")
        case 384: return _hex("fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff")
        default: return _hex("01" + String(repeating: "ff", count: 65))
        }
    }
    static func _hex(_ s: String) -> [UInt8] {
        var out: [UInt8] = [], it = s.makeIterator()
        while let a = it.next(), let b = it.next() { out.append(UInt8(String([a, b]), radix: 16)!) }
        return out
    }
    static func sub(_ a: [UInt8], _ b: [UInt8]) -> [UInt8] {     // a - b, same length, a >= b
        var out = a, borrow = 0
        for i in stride(from: a.count - 1, through: 0, by: -1) {
            var v = Int(a[i]) - Int(b[i]) - borrow
            borrow = v < 0 ? 1 : 0; if v < 0 { v += 256 }
            out[i] = UInt8(v)
        }
        return out
    }
    static func less(_ a: [UInt8], _ b: [UInt8]) -> Bool { a.lexicographicallyPrecedes(b) }
    /// y is "compact" when y <= p - y
    static func isCompact(_ curve: Int32, _ q: [UInt8]) -> Bool {
        let n = _EC.size(curve), y = Array(q.suffix(n))
        return !less(sub(prime(curve), y), y)
    }
    static func compact(_ curve: Int32, _ q: [UInt8]) -> [UInt8]? {
        isCompact(curve, q) ? Array(q[1...(_EC.size(curve))]) : nil
    }
    static func fromCompact(_ curve: Int32, _ x: [UInt8]) throws -> [UInt8] {
        guard x.count == _EC.size(curve) else { throw CryptoKitError.incorrectKeySize }
        let even = try _EC.importPublic(curve, [2] + x)
        if isCompact(curve, even) { return even }
        return try _EC.importPublic(curve, [3] + x)
    }
    static func generate(_ curve: Int32, compact: Bool) -> (d: [UInt8], q: [UInt8]) {
        while true {
            let d = _EC.generate(curve), q = try! _EC.publicKey(curve, d)
            if !compact || isCompact(curve, q) { return (d, q) }
        }
    }
}


extension P256.Signing.PrivateKey {
    public init<Bytes: ContiguousBytes>(derRepresentation data: Bytes) throws {
        try self.init(rawRepresentation: try _ECKeyCoding.privateScalar(256, _bytes(data)))
    }
    public init(pemRepresentation pem: String) throws {
        try self.init(derRepresentation: try _ECKeyCoding.pemBody(pem))
    }
    /// PKCS#8 (PrivateKeyInfo) DER
    public var derRepresentation: Data { Data(_ECKeyCoding.pkcs8(256, d: _bytes(rawRepresentation), q: _bytes(publicKey.x963Representation))) }
    public var pemRepresentation: String { _pem(_bytes(derRepresentation), "PRIVATE KEY") }
}
extension P256.Signing.PublicKey {
    /// the x coordinate when y is the smaller square root (always for keys created with compactRepresentable: true)
    public var compactRepresentation: Data? { _ECKeyCoding.compact(256, _bytes(x963Representation)).map { Data($0) } }
    public init<Bytes: ContiguousBytes>(compactRepresentation data: Bytes) throws {
        try self.init(x963Representation: try _ECKeyCoding.fromCompact(256, _bytes(data)))
    }
}

extension P256.KeyAgreement.PrivateKey {
    public init<Bytes: ContiguousBytes>(derRepresentation data: Bytes) throws {
        try self.init(rawRepresentation: try _ECKeyCoding.privateScalar(256, _bytes(data)))
    }
    public init(pemRepresentation pem: String) throws {
        try self.init(derRepresentation: try _ECKeyCoding.pemBody(pem))
    }
    /// PKCS#8 (PrivateKeyInfo) DER
    public var derRepresentation: Data { Data(_ECKeyCoding.pkcs8(256, d: _bytes(rawRepresentation), q: _bytes(publicKey.x963Representation))) }
    public var pemRepresentation: String { _pem(_bytes(derRepresentation), "PRIVATE KEY") }
}
extension P256.KeyAgreement.PublicKey {
    /// the x coordinate when y is the smaller square root (always for keys created with compactRepresentable: true)
    public var compactRepresentation: Data? { _ECKeyCoding.compact(256, _bytes(x963Representation)).map { Data($0) } }
    public init<Bytes: ContiguousBytes>(compactRepresentation data: Bytes) throws {
        try self.init(x963Representation: try _ECKeyCoding.fromCompact(256, _bytes(data)))
    }
}

extension P384.Signing.PrivateKey {
    public init<Bytes: ContiguousBytes>(derRepresentation data: Bytes) throws {
        try self.init(rawRepresentation: try _ECKeyCoding.privateScalar(384, _bytes(data)))
    }
    public init(pemRepresentation pem: String) throws {
        try self.init(derRepresentation: try _ECKeyCoding.pemBody(pem))
    }
    /// PKCS#8 (PrivateKeyInfo) DER
    public var derRepresentation: Data { Data(_ECKeyCoding.pkcs8(384, d: _bytes(rawRepresentation), q: _bytes(publicKey.x963Representation))) }
    public var pemRepresentation: String { _pem(_bytes(derRepresentation), "PRIVATE KEY") }
}
extension P384.Signing.PublicKey {
    /// the x coordinate when y is the smaller square root (always for keys created with compactRepresentable: true)
    public var compactRepresentation: Data? { _ECKeyCoding.compact(384, _bytes(x963Representation)).map { Data($0) } }
    public init<Bytes: ContiguousBytes>(compactRepresentation data: Bytes) throws {
        try self.init(x963Representation: try _ECKeyCoding.fromCompact(384, _bytes(data)))
    }
}

extension P384.KeyAgreement.PrivateKey {
    public init<Bytes: ContiguousBytes>(derRepresentation data: Bytes) throws {
        try self.init(rawRepresentation: try _ECKeyCoding.privateScalar(384, _bytes(data)))
    }
    public init(pemRepresentation pem: String) throws {
        try self.init(derRepresentation: try _ECKeyCoding.pemBody(pem))
    }
    /// PKCS#8 (PrivateKeyInfo) DER
    public var derRepresentation: Data { Data(_ECKeyCoding.pkcs8(384, d: _bytes(rawRepresentation), q: _bytes(publicKey.x963Representation))) }
    public var pemRepresentation: String { _pem(_bytes(derRepresentation), "PRIVATE KEY") }
}
extension P384.KeyAgreement.PublicKey {
    /// the x coordinate when y is the smaller square root (always for keys created with compactRepresentable: true)
    public var compactRepresentation: Data? { _ECKeyCoding.compact(384, _bytes(x963Representation)).map { Data($0) } }
    public init<Bytes: ContiguousBytes>(compactRepresentation data: Bytes) throws {
        try self.init(x963Representation: try _ECKeyCoding.fromCompact(384, _bytes(data)))
    }
}

extension P521.Signing.PrivateKey {
    public init<Bytes: ContiguousBytes>(derRepresentation data: Bytes) throws {
        try self.init(rawRepresentation: try _ECKeyCoding.privateScalar(521, _bytes(data)))
    }
    public init(pemRepresentation pem: String) throws {
        try self.init(derRepresentation: try _ECKeyCoding.pemBody(pem))
    }
    /// PKCS#8 (PrivateKeyInfo) DER
    public var derRepresentation: Data { Data(_ECKeyCoding.pkcs8(521, d: _bytes(rawRepresentation), q: _bytes(publicKey.x963Representation))) }
    public var pemRepresentation: String { _pem(_bytes(derRepresentation), "PRIVATE KEY") }
}
extension P521.Signing.PublicKey {
    /// the x coordinate when y is the smaller square root (always for keys created with compactRepresentable: true)
    public var compactRepresentation: Data? { _ECKeyCoding.compact(521, _bytes(x963Representation)).map { Data($0) } }
    public init<Bytes: ContiguousBytes>(compactRepresentation data: Bytes) throws {
        try self.init(x963Representation: try _ECKeyCoding.fromCompact(521, _bytes(data)))
    }
}

extension P521.KeyAgreement.PrivateKey {
    public init<Bytes: ContiguousBytes>(derRepresentation data: Bytes) throws {
        try self.init(rawRepresentation: try _ECKeyCoding.privateScalar(521, _bytes(data)))
    }
    public init(pemRepresentation pem: String) throws {
        try self.init(derRepresentation: try _ECKeyCoding.pemBody(pem))
    }
    /// PKCS#8 (PrivateKeyInfo) DER
    public var derRepresentation: Data { Data(_ECKeyCoding.pkcs8(521, d: _bytes(rawRepresentation), q: _bytes(publicKey.x963Representation))) }
    public var pemRepresentation: String { _pem(_bytes(derRepresentation), "PRIVATE KEY") }
}
extension P521.KeyAgreement.PublicKey {
    /// the x coordinate when y is the smaller square root (always for keys created with compactRepresentable: true)
    public var compactRepresentation: Data? { _ECKeyCoding.compact(521, _bytes(x963Representation)).map { Data($0) } }
    public init<Bytes: ContiguousBytes>(compactRepresentation data: Bytes) throws {
        try self.init(x963Representation: try _ECKeyCoding.fromCompact(521, _bytes(data)))
    }
}
