#!/usr/bin/env bash
# Builds the isim simulator: host runtime (Linux ELF), SDK sysroot with self-authored
# headers + Mach-O frameworks (iOS-simulator x86_64), and the sample apps.
# No Apple SDK or Apple binaries are used.
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
OUT=$PWD/out
SDK=$OUT/sdk
CC=${CLANG:-clang}
LD=${LD64:-ld64.lld}
MINOS=15.0
mkdir -p "$OUT/bin" "$SDK/usr/lib" "$SDK/System/Library/Frameworks"

step() { printf '\n== %s\n' "$*"; }

step "host runtime"
PKGS="sdl3 cairo pangocairo pangoft2 fontconfig librsvg-2.0 gdk-pixbuf-2.0"
$CC -O2 -g -Wall -Wextra -Wno-unused-parameter -std=gnu11 -o "$OUT/bin/isim-runtime" \
    runtime/loader.c runtime/libsystem.c runtime/objc_rt.c runtime/host.c runtime/host_image.c runtime/host_audio.c runtime/host_net.c runtime/host_crypto.c runtime/host_sqlite.c runtime/host_os.c runtime/host_regex.c runtime/host_paint.c runtime/host_media.c \
    $(pkg-config --cflags --libs $PKGS) -lm -lpthread -ldl

step "SDK headers"
rsync -a --delete sdk-src/usr/include/ "$SDK/usr/include/"
cp sdk-src/SDKSettings.json "$SDK/"
# libc++ headers (llvmorg-22.1.8, third_party/llvm-project) configured for isim
LIBCXX=${LIBCXX_SRC:-../third_party/llvm-project}
if [ -d "$LIBCXX/libcxx/include" ]; then
  mkdir -p "$SDK/usr/include/c++/v1"
  rsync -a --delete --exclude='*.in' --exclude=CMakeLists.txt "$LIBCXX/libcxx/include/" "$SDK/usr/include/c++/v1/"
  cp sdk-src/libcxx/__config_site "$SDK/usr/include/c++/v1/__config_site"
  cp "$LIBCXX/libcxx/vendor/llvm/default_assertion_handler.in" "$SDK/usr/include/c++/v1/__assertion_handler"
  cp "$LIBCXX"/libcxxabi/include/*.h "$SDK/usr/include/c++/v1/"
fi

step "host library stubs (.tbd generated from the runtime's export tables)"
gen_tbd() { # install-name out.tbd
  local syms
  syms=$("$OUT/bin/isim-runtime" --print-exports "$1" | awk '{print $1}' | paste -sd, | sed 's/,/, /g')
  cat > "$2" <<TBD
--- !tapi-tbd
# GENERATED by isim/build.sh from isim-runtime's host tables. Not an Apple SDK file.
tbd-version:     4
targets:         [ x86_64-ios-simulator ]
install-name:    '$1'
exports:
  - targets:     [ x86_64-ios-simulator ]
    symbols:     [ $syms ]
...
TBD
}
gen_tbd /usr/lib/libSystem.B.dylib "$SDK/usr/lib/libSystem.tbd"
gen_tbd /usr/lib/libobjc.A.dylib "$SDK/usr/lib/libobjc.tbd"
gen_tbd /usr/lib/libisim_host.dylib "$SDK/usr/lib/libisim_host.tbd"
gen_tbd /usr/lib/libsqlite3.dylib "$SDK/usr/lib/libsqlite3.tbd"

# common guest flags: iOS-simulator target, our sysroot headers only
GUEST_CFLAGS=(-target x86_64-apple-ios$MINOS-simulator -nostdlibinc -isystem "$SDK/usr/include"
              -iframework "$SDK/System/Library/Frameworks" -O1 -g -fobjc-runtime=ios-$MINOS
              -Wall -Wno-unused-parameter -Wno-objc-designated-initializers -Wno-missing-noescape -Wno-mismatched-parameter-types -fno-stack-protector)
export GUEST_LDFLAGS="-arch x86_64 -platform_version ios-simulator $MINOS 0"

framework() { # Name srcdir [extra ld args...]
  local name=$1 src=$2; shift 2
  local fw="$SDK/System/Library/Frameworks/$name.framework" objdir="$OUT/obj/$name"
  mkdir -p "$fw/Headers" "$objdir"
  rsync -a --delete "sdk-src/Frameworks/$name/" "$fw/Headers/"
  mkdir -p "$fw/Modules"
  printf 'framework module %s [system] [extern_c] {\n  umbrella header "%s.h"\n  export *\n  module * { export * }\n}\n' "$name" "$name" > "$fw/Modules/module.modulemap"
  compgen -G "$src/*.[mc]" >/dev/null || { step "framework $name: headers only"; return 0; }
  step "framework $name"
  local objs=()
  for f in "$src"/*.m "$src"/*.c; do
    [ -e "$f" ] || continue
    local o="$objdir/$(basename "$f").o" arc=
    case "$f" in *.mrc.m) arc=-fno-objc-arc ;; *.m) arc=-fobjc-arc ;; esac
    $CC "${GUEST_CFLAGS[@]}" $arc -I"$src" -c "$f" -o "$o"
    objs+=("$o")
  done
  $LD $GUEST_LDFLAGS -dylib -install_name "/System/Library/Frameworks/$name.framework/$name" \
      -o "$fw/$name" "${objs[@]}" -L"$SDK/usr/lib" -F"$SDK/System/Library/Frameworks" -lSystem -lobjc "$@"
}

framework CoreFoundation frameworks/CoreFoundation
framework CoreGraphics frameworks/CoreGraphics -lisim_host
framework Foundation frameworks/Foundation -framework CoreGraphics -lisim_host
framework CoreText frameworks/CoreText -framework Foundation -lisim_host
framework UIKit frameworks/UIKit -framework Foundation -framework CoreGraphics -lisim_host
framework UserNotifications frameworks/UserNotifications -framework Foundation -framework UIKit -framework CoreGraphics -lisim_host

# install the isim tool
[ -f tools/isim ] && install -m 755 tools/isim "$OUT/bin/isim"
install -m 755 tools/isim-build.py "$OUT/bin/isim-build.py"; install -m 755 tools/isim-services.py "$OUT/bin/isim-services.py"; install -m 644 tools/xcodeproj.py "$OUT/bin/xcodeproj.py"

step "swift"
bash swift/build.sh

step "system apps (home screen, Settings)"
ISIM_SDK=$SDK ISIM_CC=$CC bash system/build.sh

for app in samples/*/ tests/*/; do
  [ -f "$app/build.sh" ] || continue
  step "sample $(basename "$app")"
  ISIM_SDK=$SDK ISIM_CC=$CC ISIM_LD=$LD bash "$app/build.sh" "$OUT/apps"
done
step "done: $OUT"
