/* Generates tests/security/HPKEVectors.swift: HPKE (RFC 9180) messages sealed by OpenSSL's independent HPKE
 * implementation, which SecurityTest opens with isim's CryptoKit HPKE.Recipient (interoperability, not a
 * self-round-trip). Run by hand:  cc make-hpke-vectors.c -lcrypto -o /tmp/hv && /tmp/hv > ../HPKEVectors.swift
 * Keys come from fixed IKM (deterministic); test-only. */
#include <openssl/evp.h>
#include <openssl/hpke.h>
#include <openssl/core_names.h>
#include <openssl/bn.h>
#include <stdio.h>
#include <string.h>

static void hex(const char *name, const unsigned char *b, size_t n) {
    printf("        \"%s\": \"", name);
    for (size_t i = 0; i < n; i++) printf("%02x", b[i]);
    printf("\",\n");
}
static size_t raw_private(EVP_PKEY *k, int x25519, unsigned char *out) {
    size_t n = 32;
    if (x25519) { EVP_PKEY_get_raw_private_key(k, out, &n); return n; }
    BIGNUM *d = NULL; EVP_PKEY_get_bn_param(k, OSSL_PKEY_PARAM_PRIV_KEY, &d);
    BN_bn2binpad(d, out, 32); BN_free(d); return 32;
}
static void vector(const char *name, OSSL_HPKE_SUITE suite, int x25519, int mode) {
    unsigned char ikmR[32], ikmE[32], ikmS[32];
    memset(ikmR, 0x11, 32); memset(ikmE, 0x22, 32); memset(ikmS, 0x33, 32);
    unsigned char pubR[133], pubS[133]; size_t pubRlen = sizeof pubR, pubSlen = sizeof pubS;
    EVP_PKEY *privR = NULL, *privS = NULL;
    OSSL_HPKE_keygen(suite, pubR, &pubRlen, &privR, ikmR, 32, NULL, NULL);
    OSSL_HPKE_keygen(suite, pubS, &pubSlen, &privS, ikmS, 32, NULL, NULL);
    OSSL_HPKE_CTX *ctx = OSSL_HPKE_CTX_new(mode, suite, OSSL_HPKE_ROLE_SENDER, NULL, NULL);
    OSSL_HPKE_CTX_set1_ikme(ctx, ikmE, 32);
    const unsigned char psk[32] = "isim pre-shared key 0123456789!!";
    if (mode == OSSL_HPKE_MODE_PSK || mode == OSSL_HPKE_MODE_PSKAUTH) OSSL_HPKE_CTX_set1_psk(ctx, "isim-psk", psk, 32);
    if (mode == OSSL_HPKE_MODE_AUTH || mode == OSSL_HPKE_MODE_PSKAUTH) OSSL_HPKE_CTX_set1_authpriv(ctx, privS);
    const unsigned char info[] = "isim HPKE test", aad[] = "header";
    unsigned char enc[133]; size_t enclen = sizeof enc;
    if (!OSSL_HPKE_encap(ctx, enc, &enclen, pubR, pubRlen, info, sizeof info - 1)) { fprintf(stderr, "encap failed\n"); return; }
    const unsigned char pt1[] = "first message from OpenSSL", pt2[] = "second message";
    unsigned char ct1[128], ct2[128]; size_t ct1len = sizeof ct1, ct2len = sizeof ct2;
    OSSL_HPKE_seal(ctx, ct1, &ct1len, aad, sizeof aad - 1, pt1, sizeof pt1 - 1);
    OSSL_HPKE_seal(ctx, ct2, &ct2len, NULL, 0, pt2, sizeof pt2 - 1);
    unsigned char exported[32];
    OSSL_HPKE_export(ctx, exported, 32, (const unsigned char *)"isim exporter", 13);
    unsigned char skR[32], skS[32];
    raw_private(privR, x25519, skR); raw_private(privS, x25519, skS);
    printf("    [\n        \"name\": \"%s\",\n        \"mode\": \"%d\",\n", name, mode);
    hex("skR", skR, 32); hex("pkS", pubS, pubSlen); hex("enc", enc, enclen);
    hex("ct1", ct1, ct1len); hex("ct2", ct2, ct2len); hex("exported", exported, 32);
    printf("    ],\n");
    OSSL_HPKE_CTX_free(ctx); EVP_PKEY_free(privR); EVP_PKEY_free(privS);
}
int main(void) {
    printf("// GENERATED by tests/security/pki/make-hpke-vectors.c with OpenSSL's HPKE (independent implementation). Do not edit.\n");
    printf("// info \"isim HPKE test\", aad \"header\" (first message only), psk \"isim pre-shared key 0123456789!!\" / id \"isim-psk\",\n");
    printf("// plaintexts \"first message from OpenSSL\" and \"second message\", export context \"isim exporter\" (32 bytes).\n");
    printf("let hpkeVectors: [[String: String]] = [\n");
    OSSL_HPKE_SUITE p256 = { OSSL_HPKE_KEM_ID_P256, OSSL_HPKE_KDF_ID_HKDF_SHA256, OSSL_HPKE_AEAD_ID_AES_GCM_256 };
    OSSL_HPKE_SUITE x25519 = { OSSL_HPKE_KEM_ID_X25519, OSSL_HPKE_KDF_ID_HKDF_SHA256, OSSL_HPKE_AEAD_ID_CHACHA_POLY1305 };
    vector("P256_SHA256_AES_GCM_256 base", p256, 0, OSSL_HPKE_MODE_BASE);
    vector("P256_SHA256_AES_GCM_256 psk", p256, 0, OSSL_HPKE_MODE_PSK);
    vector("P256_SHA256_AES_GCM_256 auth", p256, 0, OSSL_HPKE_MODE_AUTH);
    vector("Curve25519_SHA256_ChachaPoly base", x25519, 1, OSSL_HPKE_MODE_BASE);
    vector("Curve25519_SHA256_ChachaPoly authpsk", x25519, 1, OSSL_HPKE_MODE_PSKAUTH);
    printf("]\n");
    return 0;
}
