/* Built-in word lists for isim's UITextChecker, autocorrection and the predictive bar (self-authored lists of
 * common words; space separated, lower case). Small on purpose: see UITextChecker.h for how unknown words count. */
const char *const isim_words_en =
    "a able about above accept across act action actually add address after afternoon again against age ago agree "
    "air all allow almost alone along already also although always am amazing among amount an and angry animal "
    "another answer any anyone anything app apple apps are area arm around arrive art article as ask at attack "
    "attention aunt author autumn available avoid away baby back bad bag ball bank bar base basket bath be beach "
    "bear beautiful because become bed bedroom been beer before begin behind being believe bell below best better "
    "between big bike bill bird birthday bit black blue board boat body book born both bottle bottom box boy brain "
    "bread break breakfast bring brother brown build building bus business busy but butter button buy by cake "
    "call calm came camera can cancel cannot car card care careful carry case cat catch center chair chance change "
    "cheap check cheese chicken child children choose church city class clean clear click clock close clothes "
    "cloud club coffee cold collect color come comfortable common company complete computer condition contact "
    "continue control cook cool copy corner correct cost could count country course cousin cover cream create cross "
    "cup cut dad dance dangerous dark data date daughter day dead deal dear decide deep delete design desk detail "
    "did die different difficult dinner direction dirty discover do doctor does dog doing done door down draw "
    "dream dress drink drive drop dry during each ear early earth easy eat edit egg eight either else email empty "
    "end energy enjoy enough enter error even evening event ever every everyone everything exactly example excited "
    "exercise expensive explain eye face fact fall family famous far farm fast fat father favorite feel few field "
    "file fill film final find fine finger finish fire first fish five fix floor flower fly follow food foot for "
    "forget form forward four free fresh friend from front fruit full fun funny game garden gave get gift girl "
    "give glad glass go god going gold good got great green group grow guess guitar had hair half hand happen happy "
    "hard has hat have he head health hear heart heavy hello help her here high hill him his history hold holiday "
    "home hope horse hospital hot hotel hour house how however huge human hundred hungry hurry husband i ice idea "
    "if image important in include information inside instead interest interesting into is island it item its "
    "job join journey juice jump just keep key keyboard kid kind king kitchen knew know lady lake land language "
    "large last late later laugh learn least leave left leg less lesson let letter library life light like line "
    "list listen little live long look lose lost lot love low lunch machine made main make man many map market "
    "matter may maybe me meal mean meet meeting memory menu message middle might milk mind minute miss mistake "
    "model mom moment money month moon more morning most mother mountain mouse mouth move movie much music must "
    "my name near need never new news next nice night nine no noise none normal north nose not note nothing "
    "notice now number of off offer office often oh ok okay old on once one only open or orange order other our "
    "out outside over own page pain paint paper parent park part party pass past pay pen pencil people perfect "
    "perhaps person phone photo picture piece place plan plane plant play please pocket point police poor popular "
    "possible post power present pretty price print problem program project put question quick quickly quiet "
    "quite rain read ready real really reason receive red remember repeat reply rest restaurant return rich ride "
    "right river road room round rule run sad safe said salt same save saw say school sea search season seat "
    "second see seem sell send sentence serious set seven several shall share she shirt shoe shop short should "
    "show shower side sign simple since sing sister sit six size skill sky sleep slow small smile snow so some "
    "someone something sometimes son song soon sorry sound soup south space speak special spell spend sport "
    "spring stand star start station stay step still stop store story street strong student study style such "
    "sugar summer sun sure surprise sweet swim system table take talk tall taste tea teach teacher team tell ten "
    "test text than thank thanks that the their them then there these they thing think third this those though "
    "thought three through ticket time tired to today together told tomorrow tonight too took top touch town toy "
    "train travel tree trip true try turn twelve two type under understand until up upon us use useful usually "
    "very video view visit voice wait walk wall want warm was wash watch water way we wear weather week weekend "
    "welcome well went were west what when where which while white who whole why wife will win window winter "
    "wish with without woman wonderful word work world worry would write wrong year yellow yes yesterday yet you "
    "young your yourself zero quickly brown fox jumps lazy dog jumped over hello world swift";
const char *const isim_words_pt =
    "a agora ainda algo algum alguma amanha amigo amiga amor ano antes ao aqui arroz as assim até aula azul "
    "bem boa bom bonito branco cabeça cada café cama caminho carro casa cedo certo cidade coisa com como "
    "comprar conta contra coracao corpo da dar de depois dia dinheiro disse do dois dormir e ela ele eles em "
    "embora entao entre escola está estar este esta eu fazer feliz filho filha fim foi fora frio gente gostar "
    "grande hoje homem hora isso isto já lá lado leite livro longe lugar mais mae mãe mas me menino "
    "menina mesa mesmo meu minha muito mulher mundo não nada noite nome nos nosso nova novo o obrigado obrigada "
    "olha onde ontem os ou olá pão para parte pai pela pelo pessoa pode por porque porta pouco primeiro "
    "quando quanto que quem querer rua sabe saber se sem sempre ser seu sim sobre sol sua também tarde tem "
    "tempo ter teu tudo um uma vai vez vida você voltar água bom-dia boa-noite coração "
    "amanhã então estão estávamos irmão irmã cafés espaço retorno";
const char *const isim_words_es =
    "a agua ahora al algo alguno alguna amigo amiga año antes aquí así azul bien blanco bueno buena "
    "cada café calle cama casa ciudad coche como con contra cosa cuando cuanto de del después día "
    "dinero donde dos el él ella ellos en entre es esa ese eso esta este está estar familia feliz fin "
    "gracias grande gente hablar hacer hay hijo hija hola hombre hora hoy ir la le leche libro lo los luego "
    "madre mal mañana mas más me mesa mi mucho mujer mundo muy nada niño niña no noche nombre "
    "nosotros nuevo nueva o otro otra padre pan para pero persona poco poder por porque primero puerta que "
    "qué querer quien saber se ser si sí siempre sin sobre sol su también tarde tener tiempo todo "
    "trabajo tu tú un una uno usted vamos vez vida y ya yo espacio intro señor señora español";
const char *const isim_words_fr =
    "a à aller ami amie année après au aujourd'hui aussi autre avec avoir beau beaucoup bien blanc "
    "bleu bon bonjour bonne bonsoir c'est ca ça café chaque chat chez chose ciel comme comment dans de "
    "demain depuis des deux dire donc du eau elle elles en encore enfant est et être fait faire famille femme "
    "fille fils fin fois gens grand grande homme ici il ils je jour journée la le les leur lui ma main mais "
    "maison mal mère merci mes mieux moi mon monde nous nouveau nouvelle nuit oui ou où pain par parce "
    "pas père petit peu peut plus pour pourquoi premier quand que qui rien rue sans ses si soir son sont sur "
    "ta temps toi ton tout très travail tu un une vie ville voiture vous voir vrai espace retour été "
    "école écrire français garçon";
const char *const isim_words_de =
    "aber alle allem als also alt am an and ander andere arbeit auch auf aus auto bei beim bis bitte bleiben "
    "brot da danke dann das dass dein deine dem den der des dich die dir doch dort drei du durch ein eine einen "
    "einem einer er es essen etwas euch frau freund freundin für ganz gehen gern gut guten haben hallo haus "
    "heute hier hund ich ihm ihn ihr im immer in ist ja jahr jetzt kann katze kein keine kind kommen können "
    "leben machen mann mehr mein meine mich mir mit morgen mutter müssen nach nacht nein neu nicht nichts "
    "noch nun nur oder ohne schon schule sehr sein seine sich sie sind so stadt tag tisch und uns unser vater "
    "viel vielleicht vom von vor wann warum was wasser weil welt wenn wer wie wieder wir wo zeit zu zum zur zwei "
    "leerzeichen grüße schön über straße mädchen";
