/* GENERATED from sqlite3.h (SQLite 3.53.4, public domain): the C API exported by isim's /usr/lib/libsqlite3.dylib.
 * F = function, D = data symbol. Regenerate when updating isim/sdk-src/usr/include/sqlite3.h. */
F(sqlite3_activate_cerod) F(sqlite3_aggregate_context) F(sqlite3_aggregate_count) F(sqlite3_auto_extension)
F(sqlite3_autovacuum_pages) F(sqlite3_backup_finish) F(sqlite3_backup_init) F(sqlite3_backup_pagecount)
F(sqlite3_backup_remaining) F(sqlite3_backup_step) F(sqlite3_bind_blob) F(sqlite3_bind_blob64) F(sqlite3_bind_double)
F(sqlite3_bind_int) F(sqlite3_bind_int64) F(sqlite3_bind_null) F(sqlite3_bind_parameter_count)
F(sqlite3_bind_parameter_index) F(sqlite3_bind_parameter_name) F(sqlite3_bind_pointer) F(sqlite3_bind_text)
F(sqlite3_bind_text16) F(sqlite3_bind_text64) F(sqlite3_bind_value) F(sqlite3_bind_zeroblob)
F(sqlite3_bind_zeroblob64) F(sqlite3_blob_bytes) F(sqlite3_blob_close) F(sqlite3_blob_open) F(sqlite3_blob_read)
F(sqlite3_blob_reopen) F(sqlite3_blob_write) F(sqlite3_busy_handler) F(sqlite3_busy_timeout)
F(sqlite3_cancel_auto_extension) F(sqlite3_carray_bind) F(sqlite3_carray_bind_v2) F(sqlite3_changes)
F(sqlite3_changes64) F(sqlite3_clear_bindings) F(sqlite3_close) F(sqlite3_close_v2) F(sqlite3_collation_needed)
F(sqlite3_collation_needed16) F(sqlite3_column_blob) F(sqlite3_column_bytes) F(sqlite3_column_bytes16)
F(sqlite3_column_count) F(sqlite3_column_database_name) F(sqlite3_column_database_name16) F(sqlite3_column_decltype)
F(sqlite3_column_decltype16) F(sqlite3_column_double) F(sqlite3_column_int) F(sqlite3_column_int64)
F(sqlite3_column_name) F(sqlite3_column_name16) F(sqlite3_column_origin_name) F(sqlite3_column_origin_name16)
F(sqlite3_column_table_name) F(sqlite3_column_table_name16) F(sqlite3_column_text) F(sqlite3_column_text16)
F(sqlite3_column_type) F(sqlite3_column_value) F(sqlite3_commit_hook) F(sqlite3_compileoption_get)
F(sqlite3_compileoption_used) F(sqlite3_complete) F(sqlite3_complete16) F(sqlite3_config)
F(sqlite3_context_db_handle) F(sqlite3_create_collation) F(sqlite3_create_collation16) F(sqlite3_create_collation_v2)
F(sqlite3_create_filename) F(sqlite3_create_function) F(sqlite3_create_function16) F(sqlite3_create_function_v2)
F(sqlite3_create_module) F(sqlite3_create_module_v2) F(sqlite3_create_window_function) F(sqlite3_data_count)
F(sqlite3_database_file_object) F(sqlite3_db_cacheflush) F(sqlite3_db_config) F(sqlite3_db_filename)
F(sqlite3_db_handle) F(sqlite3_db_mutex) F(sqlite3_db_name) F(sqlite3_db_readonly) F(sqlite3_db_release_memory)
F(sqlite3_db_status) F(sqlite3_db_status64) F(sqlite3_declare_vtab) F(sqlite3_deserialize) F(sqlite3_drop_modules)
F(sqlite3_enable_load_extension) F(sqlite3_enable_shared_cache) F(sqlite3_errcode) F(sqlite3_errmsg)
F(sqlite3_errmsg16) F(sqlite3_error_offset) F(sqlite3_errstr) F(sqlite3_exec) F(sqlite3_expanded_sql)
F(sqlite3_expired) F(sqlite3_extended_errcode) F(sqlite3_extended_result_codes) F(sqlite3_file_control)
F(sqlite3_filename_database) F(sqlite3_filename_journal) F(sqlite3_filename_wal) F(sqlite3_finalize) F(sqlite3_free)
F(sqlite3_free_filename) F(sqlite3_free_table) F(sqlite3_get_autocommit) F(sqlite3_get_auxdata)
F(sqlite3_get_clientdata) F(sqlite3_get_table) F(sqlite3_global_recover) F(sqlite3_hard_heap_limit64)
F(sqlite3_initialize) F(sqlite3_interrupt) F(sqlite3_is_interrupted) F(sqlite3_keyword_check)
F(sqlite3_keyword_count) F(sqlite3_keyword_name) F(sqlite3_last_insert_rowid) F(sqlite3_libversion)
F(sqlite3_libversion_number) F(sqlite3_limit) F(sqlite3_load_extension) F(sqlite3_log) F(sqlite3_malloc)
F(sqlite3_malloc64) F(sqlite3_memory_alarm) F(sqlite3_memory_highwater) F(sqlite3_memory_used) F(sqlite3_mprintf)
F(sqlite3_msize) F(sqlite3_mutex_alloc) F(sqlite3_mutex_enter) F(sqlite3_mutex_free) F(sqlite3_mutex_held)
F(sqlite3_mutex_leave) F(sqlite3_mutex_notheld) F(sqlite3_mutex_try) F(sqlite3_next_stmt) F(sqlite3_normalized_sql)
F(sqlite3_open) F(sqlite3_open16) F(sqlite3_open_v2) F(sqlite3_os_end) F(sqlite3_os_init)
F(sqlite3_overload_function) F(sqlite3_prepare) F(sqlite3_prepare16) F(sqlite3_prepare16_v2) F(sqlite3_prepare16_v3)
F(sqlite3_prepare_v2) F(sqlite3_prepare_v3) F(sqlite3_preupdate_blobwrite) F(sqlite3_preupdate_count)
F(sqlite3_preupdate_depth) F(sqlite3_preupdate_hook) F(sqlite3_preupdate_new) F(sqlite3_preupdate_old)
F(sqlite3_profile) F(sqlite3_progress_handler) F(sqlite3_randomness) F(sqlite3_realloc) F(sqlite3_realloc64)
F(sqlite3_release_memory) F(sqlite3_reset) F(sqlite3_reset_auto_extension) F(sqlite3_result_blob)
F(sqlite3_result_blob64) F(sqlite3_result_double) F(sqlite3_result_error) F(sqlite3_result_error16)
F(sqlite3_result_error_code) F(sqlite3_result_error_nomem) F(sqlite3_result_error_toobig) F(sqlite3_result_int)
F(sqlite3_result_int64) F(sqlite3_result_null) F(sqlite3_result_pointer) F(sqlite3_result_subtype)
F(sqlite3_result_text) F(sqlite3_result_text16) F(sqlite3_result_text16be) F(sqlite3_result_text16le)
F(sqlite3_result_text64) F(sqlite3_result_value) F(sqlite3_result_zeroblob) F(sqlite3_result_zeroblob64)
F(sqlite3_rollback_hook) F(sqlite3_rtree_geometry_callback) F(sqlite3_rtree_query_callback) F(sqlite3_serialize)
F(sqlite3_set_authorizer) F(sqlite3_set_auxdata) F(sqlite3_set_clientdata) F(sqlite3_set_errmsg)
F(sqlite3_set_last_insert_rowid) F(sqlite3_setlk_timeout) F(sqlite3_shutdown) F(sqlite3_sleep)
F(sqlite3_snapshot_cmp) F(sqlite3_snapshot_free) F(sqlite3_snapshot_get) F(sqlite3_snapshot_open)
F(sqlite3_snapshot_recover) F(sqlite3_snprintf) F(sqlite3_soft_heap_limit) F(sqlite3_soft_heap_limit64)
F(sqlite3_sourceid) F(sqlite3_sql) F(sqlite3_status) F(sqlite3_status64) F(sqlite3_step) F(sqlite3_stmt_busy)
F(sqlite3_stmt_explain) F(sqlite3_stmt_isexplain) F(sqlite3_stmt_readonly) F(sqlite3_stmt_scanstatus)
F(sqlite3_stmt_scanstatus_reset) F(sqlite3_stmt_scanstatus_v2) F(sqlite3_stmt_status) F(sqlite3_str_append)
F(sqlite3_str_appendall) F(sqlite3_str_appendchar) F(sqlite3_str_appendf) F(sqlite3_str_errcode)
F(sqlite3_str_finish) F(sqlite3_str_free) F(sqlite3_str_length) F(sqlite3_str_new) F(sqlite3_str_reset)
F(sqlite3_str_truncate) F(sqlite3_str_value) F(sqlite3_str_vappendf) F(sqlite3_strglob) F(sqlite3_stricmp)
F(sqlite3_strlike) F(sqlite3_strnicmp) F(sqlite3_system_errno) F(sqlite3_table_column_metadata)
F(sqlite3_test_control) F(sqlite3_thread_cleanup) F(sqlite3_threadsafe) F(sqlite3_total_changes)
F(sqlite3_total_changes64) F(sqlite3_trace) F(sqlite3_trace_v2) F(sqlite3_transfer_bindings) F(sqlite3_txn_state)
F(sqlite3_unlock_notify) F(sqlite3_update_hook) F(sqlite3_uri_boolean) F(sqlite3_uri_int64) F(sqlite3_uri_key)
F(sqlite3_uri_parameter) F(sqlite3_user_data) F(sqlite3_value_blob) F(sqlite3_value_bytes) F(sqlite3_value_bytes16)
F(sqlite3_value_double) F(sqlite3_value_dup) F(sqlite3_value_encoding) F(sqlite3_value_free)
F(sqlite3_value_frombind) F(sqlite3_value_int) F(sqlite3_value_int64) F(sqlite3_value_nochange)
F(sqlite3_value_numeric_type) F(sqlite3_value_pointer) F(sqlite3_value_subtype) F(sqlite3_value_text)
F(sqlite3_value_text16) F(sqlite3_value_text16be) F(sqlite3_value_text16le) F(sqlite3_value_type) F(sqlite3_vfs_find)
F(sqlite3_vfs_register) F(sqlite3_vfs_unregister) F(sqlite3_vmprintf) F(sqlite3_vsnprintf) F(sqlite3_vtab_collation)
F(sqlite3_vtab_config) F(sqlite3_vtab_distinct) F(sqlite3_vtab_in) F(sqlite3_vtab_in_first) F(sqlite3_vtab_in_next)
F(sqlite3_vtab_nochange) F(sqlite3_vtab_on_conflict) F(sqlite3_vtab_rhs_value) F(sqlite3_wal_autocheckpoint)
F(sqlite3_wal_checkpoint) F(sqlite3_wal_checkpoint_v2) F(sqlite3_wal_hook) F(sqlite3_win32_set_directory)
F(sqlite3_win32_set_directory16) F(sqlite3_win32_set_directory8)
D(sqlite3_data_directory) D(sqlite3_temp_directory) D(sqlite3_version)
