#pragma once
/* isim SDK Foundation subset (self-authored; API-compatible names, not Apple's headers). */
#include <Foundation/NSObjCRuntime.h>
#import <Foundation/NSObject.h>
#import <Foundation/NSString.h>
#import <Foundation/NSValue.h>
#import <Foundation/NSIndexPath.h>
#import <Foundation/NSArray.h>
#import <Foundation/NSDictionary.h>
#import <Foundation/NSSet.h>
#import <Foundation/NSNull.h>
#import <Foundation/NSException.h>
#import <Foundation/NSError.h>
#import <Foundation/NSAutoreleasePool.h>
#import <Foundation/NSBundle.h>
#import <Foundation/NSDate.h>
#import <Foundation/NSLocale.h>
#import <Foundation/NSURL.h>
#import <Foundation/NSFileManager.h>
#import <Foundation/NSTimeZone.h>
#import <Foundation/NSFormatter.h>
#import <Foundation/NSTimer.h>
#import <Foundation/NSThread.h>
#import <Foundation/NSOperation.h>
#import <Foundation/NSCharacterSet.h>
#import <Foundation/NSRunLoop.h>
#import <Foundation/NSNotification.h>
#import <Foundation/NSLock.h>
#import <Foundation/NSProcessInfo.h>
#import <Foundation/NSUserDefaults.h>
#include <dispatch/dispatch.h>
#import <Foundation/NSCoder.h>
#import <Foundation/NSRegularExpression.h>
#import <Foundation/NSCalendar.h>
#import <Foundation/NSUnit.h>
#import <Foundation/NSMeasurement.h>
#import <Foundation/NSKeyValueCoding.h>
#import <Foundation/NSIndexSet.h>
#import <Foundation/NSOrderedCollections.h>
#import <Foundation/NSPredicate.h>
#import <Foundation/NSData.h>
#import <Foundation/NSPropertyList.h>
#import <Foundation/NSUUID.h>
#import <Foundation/NSUndoManager.h>
#import <Foundation/NSFileHandle.h>
#import <Foundation/NSAttributedString.h>
#import <Foundation/NSValueTransformer.h>
#import <Foundation/NSUbiquitousKeyValueStore.h>
