"""Writing build.ninja, finding a ninja binary, and (for CI) giving unchanged sources back their old timestamps."""
import json
import os
import shlex
import shutil
import subprocess
import sys

from . import act


def _path(p):
    return str(p).replace("$", "$$").replace(" ", "$ ").replace(":", "$:")


class Ninja:
    """A build.ninja being written. Paths are relative to the isim directory (Ninja runs there)."""

    def __init__(self):
        self.lines = ["# GENERATED by isim/build.py; do not edit.", "ninja_required_version = 1.10", "builddir = out", ""]
        self.outputs = set()
        self.rule("cmd", "$cmd", description="$desc", restat=True)
        self.rule("cc", "$cmd", description="$desc", depfile="$out.d", deps="gcc")

    def rule(self, name, command, description=None, depfile=None, deps=None, restat=False, pool=None):
        self.lines.append(f"rule {name}")
        self.lines.append(f"  command = {command}")
        for k, v in (("description", description), ("depfile", depfile), ("deps", deps), ("pool", pool)):
            if v:
                self.lines.append(f"  {k} = {v}")
        if restat:
            self.lines.append("  restat = 1")
        self.lines.append("")

    def pool(self, name, depth):
        self.lines += [f"pool {name}", f"  depth = {depth}", ""]

    def build(self, outputs, cmd, inputs=(), implicit=(), order_only=(), desc=None, rule="cmd", pool=None):
        """an edge running cmd (an argument list, or a string for the shell) to produce outputs"""
        outputs = [str(o) for o in ([outputs] if isinstance(outputs, (str, os.PathLike)) else outputs)]
        dup = self.outputs.intersection(outputs)
        if dup:
            raise SystemExit(f"build.py: {sorted(dup)[0]} is produced twice")
        self.outputs.update(outputs)
        line = f"build {' '.join(map(_path, outputs))}: {rule}"
        for group, sep in ((inputs, ""), (implicit, " |"), (order_only, " ||")):
            group = [str(x) for x in group]
            if group:
                line += sep + " " + " ".join(map(_path, group))
        self.lines.append(line)
        text = cmd if isinstance(cmd, str) else shlex.join(str(c) for c in cmd)
        self.lines.append("  cmd = " + text.replace("$", "$$").replace("\n", " "))
        self.lines.append("  desc = " + (desc or os.path.basename(outputs[0])).replace("$", "$$"))
        if pool:
            self.lines.append(f"  pool = {pool}")
        return outputs

    def phony(self, name, inputs):
        self.lines.append(f"build {name}: phony " + " ".join(_path(i) for i in inputs))

    def default(self, targets):
        self.lines.append("default " + " ".join(targets))

    def write(self, path):
        return act.write_if_changed(path, "\n".join(self.lines) + "\n")


def find_ninja(venv):
    """ninja from PATH (1.10+), else the `ninja` package in the build's virtualenv"""
    for exe in (shutil.which("ninja"), shutil.which("ninja-build"), os.path.join(venv, "bin", "ninja")):
        if exe and os.access(exe, os.X_OK):
            try:
                v = subprocess.run([exe, "--version"], capture_output=True, text=True).stdout.strip()
                if tuple(int(x) for x in v.split(".")[:2]) >= (1, 10):
                    return exe
            except (OSError, ValueError):
                pass
    return None


# ---- timestamps for restored build caches ----
# Ninja decides by modification time. A fresh checkout gives every source a new one, so a build directory restored
# from a cache (CI) would rebuild everything. After a build, record each tracked file's size, mtime and hash; before
# the next one, give files whose content is unchanged their recorded mtime back.

def _tracked(repo):
    """the checkout's files and those of the pinned third-party checkouts (third_party/*: a fresh clone gives them
    new timestamps too)"""
    files = []
    tp = os.path.join(repo, "third_party")
    for d in [repo] + sorted(os.path.join(tp, x) for x in (os.listdir(tp) if os.path.isdir(tp) else ())
                             if os.path.isdir(os.path.join(tp, x, ".git"))):
        try:
            out = subprocess.run(["git", "-C", d, "ls-files", "-z"], capture_output=True, check=True).stdout
        except (OSError, subprocess.CalledProcessError):
            continue
        files += [os.path.join(d, p) for p in out.decode().split("\0") if p]
    return files


def restore_mtimes(repo, state_path):
    try:
        with open(state_path) as f:
            state = json.load(f)
    except (OSError, ValueError):
        return 0
    restored = 0
    for p in _tracked(repo):
        rec = state.get(os.path.relpath(p, repo))
        if not rec:
            continue
        try:
            st = os.stat(p)
        except OSError:
            continue
        size, mtime, h = rec
        if st.st_mtime_ns == mtime or st.st_size != size or not os.path.isfile(p):
            continue
        if act.file_hash(p) == h:
            os.utime(p, ns=(st.st_atime_ns, mtime))
            restored += 1
    return restored


def record_mtimes(repo, state_path):
    try:
        with open(state_path) as f:
            old = json.load(f)
    except (OSError, ValueError):
        old = {}
    state = {}
    for p in _tracked(repo):
        try:
            st = os.stat(p)
        except OSError:
            continue
        if not os.path.isfile(p):
            continue
        rel = os.path.relpath(p, repo)
        rec = old.get(rel)
        h = rec[2] if rec and rec[0] == st.st_size and rec[1] == st.st_mtime_ns else act.file_hash(p)
        state[rel] = [st.st_size, st.st_mtime_ns, h]
    act.write_if_changed(state_path, json.dumps(state))


def run(ninja, root, targets, jobs=None, verbose=False, keep_going=False):
    cmd = [ninja, "-C", root, "-f", "out/build.ninja"]
    if jobs:
        cmd += ["-j", str(jobs)]
    if verbose:
        cmd.append("-v")
    if keep_going:
        cmd += ["-k", "0"]
    cmd += targets
    sys.stdout.flush()
    return subprocess.call(cmd)
