#!/usr/bin/env bash
# Build HelloSpriteKit.app (SpriteKit, GameplayKit, GameController on isim). Needs the swift:6.2 image.
# Resources (atlas, sounds, .sks archives) are generated by make-assets.py.
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"
isim=$(realpath ../../out/bin/isim)
for m in SwiftUI SpriteKit GameplayKit GameController; do
  [ -f ../../out/sdk/usr/lib/swift/libswift$m.dylib ] || { echo "HelloSpriteKit: skipped ($m not built)"; exit 0; }
done
out=${1:?output dir}/HelloSpriteKit.app; obj=$(realpath -m ../../out/swift/obj/HelloSpriteKit.o)
rm -rf "$out"; mkdir -p "$out" "$(dirname "$obj")"
"$isim" swiftc -module-name HelloSpriteKit -parse-as-library -wmo -c ./*.swift -o "$obj"
"$isim" cc "$obj" -o "$out/HelloSpriteKit"
cp Info.plist "$out/"
python3 make-assets.py "$out"
echo "built $out"
